---
- hosts: all
  become: true
  roles:
     - dhcp-server
  vars:
    dhcp_global_default_lease_time: 28800   # 8hrs
    dhcp_global_max_lease_time: 43200       # 12 hrs
    dhcp_global_domain_name: cverde.cl
    dhcp_router: 192.168.153.100
    dhcp_global_domain_name_servers: 8.8.8.8, 8.8.4.4

    #DHCP DECLARATION OPTION
    subnet_dhcp_network: '192.168.153.0'
    subnet_dhcp_subnet_mask: '255.255.255.0'
    subnet_range_start: '192.168.153.110'
    subnet_range_end: '192.168.153.120'

    #HOST DECLARATION
    hosts:
      - name: POS01
        mac_address: 00:0c:29:d2:17:e7
        ipv4_address: 192.168.153.111

      - name: POS02
        mac_address: ee:ee:ee:ee:e2:e
        ipv4_address: 192.168.153.112

      - name: POS03
        mac_address: ee:ee:ee:ee:e3:e
        ipv4_address: 192.168.153.113
        deny: true
