# roles/dhcp/tasks/main.yml
---

- name: Install packages
  package:
    name: "{{ dhcp_packages }}"
  tags: dhcp

- name: Set config directory perms
  file:
    path: "{{ dhcp_config_dir }}"
    state: directory
    mode: 0755
  tags: perms

- name: Install config file
  template:
    src: etc_dhcp_dhcpd.conf.j2
    dest: "{{ dhcp_config }}"
    owner: root
    group: root
    mode: 0644
    validate: 'dhcpd -t -cf %s'
  notify: restart dhcp
  tags: copy_file
